### ISSUE TITLE
Ubuntu 20.04: error compiling due to impossible dependencies resolution

### ISSUE THREAD

**Issue by batric** [Cygn/pulseaudio-dlna#44]
Hello, I'm trying to compile on Ubuntu 20.04.4 LTS full patch:

pulseaudio_dlna-0.6.5:
Installed /usr/local/lib/python3.8/dist-packages/pulseaudio_dlna-0.6.5-py3.8.egg
Processing dependencies for pulseaudio-dlna==0.6.5
error: **zeroconf 0.24.4 is installed but zeroconf>=0.25.1** is required by {'pychromecast'}
make: *** [Makefile:40: install] Errore 1

pulseaudio_dlna-0.6.4:
Installed /usr/local/lib/python3.8/dist-packages/pulseaudio_dlna-0.6.4-py3.8.egg
Processing dependencies for pulseaudio-dlna==0.6.4
error: **zeroconf 0.24.4 is installed but zeroconf>=0.25.1** is required by {'pychromecast'}
make: *** [Makefile:40: install] Errore 1

pulseaudio_dlna-0.6.3:
Installed /usr/local/lib/python3.8/dist-packages/pulseaudio_dlna-0.6.3-py3.8.egg
Processing dependencies for pulseaudio-dlna==0.6.3
error: **PyChromecast 10.3.0 is installed but pychromecast<10** is required by {'pulseaudio-dlna'}
make: *** [Makefile:40: install] Errore 1

It there anything to do to get compiled on ubuntu focal fossa?

Many thanks
Riccardo

**Comment by Cygn** [comment]
How did you get pychromecast 10.3 without zeroconf 0.25.1 ?? That's where your compilation errors on pa-dlna 0.6.5.
You can try something like `pip install --user --upgrade pychromecast zeroconf` to satisfy those dependencies and try to compile again. 
Or stick to a older pychromacast =< 9 and try 0.6.3 or 0.6.2

**Comment by batric** [comment]
I do not know, I didn't install/changed anything, before your version I managed to install the Masmu version.
the pip trick managed to complete the compilation.

However running the resulting binary:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (zeroconf 0.24.4 (/usr/lib/python3/dist-packages), Requirement.parse('zeroconf>=0.25.1'), {'pychromecast'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pulseaudio-dlna", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 586, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 599, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (zeroconf 0.24.4 (/usr/lib/python3/dist-packages), Requirement.parse('zeroconf>=0.25.1'), {'pychromecast'})


I suspect that there could be some leftovers from previous install, any hints how to check?

regards
Riccardo

**Comment by Cygn** [comment]
You should compile and install with`pip install --user .` Don't `sudo` and don't `make install` systemwide, it wont pick up your local libs. / 
Clean all pulseaudio from you /usr/local/* to be on the safe side.

**Comment by batric** [comment]
sorry to bother, running pip as user install fine, however make install fails:
make install
python3 setup.py install --no-compile --prefix="/usr/local"
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/local/lib/python3.8/dist-packages/test-easy-install-62724.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python3.8/dist-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://setuptools.readthedocs.io/en/latest/easy_install.html

Please make the appropriate changes for your system and try again.

make: *** [Makefile:40: install] Errore 1

that's why I compiled as root.

Following your hint of cleaning /usr/local I removed all binaries from /usr/local/(s)bin and retried compiling (as root), the traceback changed:
Traceback (most recent call last):
  File "/usr/local/bin/pulseaudio-dlna", line 11, in <module>
    load_entry_point('pulseaudio-dlna==0.6.5', 'console_scripts', 'pulseaudio-dlna')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/dist-packages/pulseaudio_dlna-0.6.5-py3.8.egg/pulseaudio_dlna/__init__.py", line 24, in <module>
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 484, in get_distribution
    raise TypeError("Expected string, Requirement, or Distribution", dist)
TypeError: ('Expected string, Requirement, or Distribution', None)

**Comment by Cygn** [comment]
as you are using an out-of-distro pychromecast and zeroconf, it won't work as root, it needs user-installed versions on those modules. Stick to user install. 
If you insist on root, you can try `sudo pip install .` but I can not guarantee that it won't break anything else.
pip handles compilation and installation - make stuff is not needed.
