### ISSUE TITLE
Error adding chromecast devices after pychromecast update to 10.0

### ISSUE THREAD

**Issue by senorsnor** [Cygn/pulseaudio-dlna#30]
I'm using Arch Linux, connecting to two chromecast devices. After updating pychromecast from 9.2.1 to 10.2.1 or 10.2.2, my chromecast devices don't get added, and the error below appears. Downgrading pychromecast to 9.2.1 resolves the issue. 

PyChromecast 10.0 introduced a breaking change on device discovery (see https://github.com/home-assistant-libs/pychromecast/releases/tag/10.0.0), specifically in this commit: https://github.com/home-assistant-libs/pychromecast/pull/556

12-25 20:41:05 pulseaudio_dlna.plugins.chromecast             INFO     ChromecastPlugin.discover()
Exception in thread zeroconf-ServiceBrowser-_googlecast._tcp-1934:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/site-packages/zeroconf/_services/browser.py", line 538, in run
    self._fire_service_state_changed_event(event)
  File "/usr/lib/python3.10/site-packages/zeroconf/_services/browser.py", line 421, in _fire_service_state_changed_event
    self._service_state_changed.fire(
  File "/usr/lib/python3.10/site-packages/zeroconf/_services/__init__.py", line 55, in fire
    h(**kwargs)
  File "/usr/lib/python3.10/site-packages/zeroconf/_services/browser.py", line 178, in on_change
    getattr(listener, _ON_CHANGE_DISPATCH[state_change])(zeroconf, service_type, name)
  File "/usr/lib/python3.10/site-packages/pychromecast/discovery.py", line 140, in add_service
    self._add_update_service(zconf, typ, name, self._cast_listener.add_cast)
  File "/usr/lib/python3.10/site-packages/pychromecast/discovery.py", line 237, in _add_update_service
    callback(uuid, name)
  File "/usr/lib/python3.10/site-packages/pychromecast/discovery.py", line 86, in add_cast
    self._add_callback(uuid, service)
  File "/usr/lib/python3.10/site-packages/pychromecast/__init__.py", line 228, in add_callback
    callback(
  File "/usr/lib/python3.10/site-packages/pulseaudio_dlna/plugins/__init__.py", line 36, in wrapper
    device = f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pulseaudio_dlna/plugins/chromecast/__init__.py", line 47, in _on_device_added
    return ChromecastRendererFactory.from_pychromecast(device)
  File "/usr/lib/python3.10/site-packages/pulseaudio_dlna/plugins/chromecast/renderer.py", line 191, in from_pychromecast
    manufacturer=pychromecast.device.manufacturer,
AttributeError: 'Chromecast' object has no attribute 'device'

- [ ]

**Comment by Cygn** [comment]
Well, it's not very nice from pychromecast. In the meantime, I've added pychromecast<10 as requirement, hoping someone will submit a patch.

**Comment by senorsnor** [comment]
It turns out to be a trivial fix, see attached patch. I've tested this here and works perfectly with PyChromecast 10.2.3.

[renderer_patch.txt](https://github.com/Cygn/pulseaudio-dlna/files/7833345/renderer_patch.txt)

I don't know how to turn this into a merge request, but perhaps with this patch you can do that? If I can be of any help please let me know!

**Comment by Cygn** [comment]
Fixed. Thx !!
